# Generated by Django 5.0.4 on 2024-05-20 02:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abilities",
            fields=[
                ("ability_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("num_holders", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "abilities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LearnedByLeveling",
            fields=[
                ("row", models.AutoField(primary_key=True, serialize=False)),
                ("level_learned", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "learned_by_leveling",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LearnedByTm",
            fields=[
                ("row", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "learned_by_tm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Moves",
            fields=[
                ("move_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("element", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("power", models.IntegerField(blank=True, null=True)),
                ("accuracy", models.IntegerField(blank=True, null=True)),
                ("pp", models.TextField(blank=True, null=True)),
                ("effect", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "moves",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NotableTrainers",
            fields=[
                ("trainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trainer_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "notable_trainers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pokedex",
            fields=[
                ("pokemon_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("details_url", models.TextField(blank=True, null=True)),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True), size=None
                    ),
                ),
                ("total", models.IntegerField(blank=True, null=True)),
                ("hp", models.IntegerField(blank=True, null=True)),
                ("atk", models.IntegerField(blank=True, null=True)),
                (
                    "def_field",
                    models.IntegerField(blank=True, db_column="def", null=True),
                ),
                ("spatk", models.IntegerField(blank=True, null=True)),
                ("spdef", models.IntegerField(blank=True, null=True)),
                ("spd", models.IntegerField(blank=True, null=True)),
                ("entry", models.TextField(blank=True, null=True)),
                ("generation", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "pokedex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PokemonAbilities",
            fields=[
                ("row", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "pokemon_abilities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PokemonRegion",
            fields=[
                ("row", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "pokemon_region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Regions",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "professor_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "generations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True), size=None
                    ),
                ),
            ],
            options={
                "db_table": "regions",
                "managed": False,
            },
        ),
    ]
