# Generated by Django 5.0.4 on 2024-05-21 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("query", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abilities",
            options={"managed": False, "verbose_name_plural": "Abilities"},
        ),
        migrations.AlterModelOptions(
            name="learnedbyleveling",
            options={"managed": False, "verbose_name_plural": "Learned By Leveling"},
        ),
        migrations.AlterModelOptions(
            name="learnedbytm",
            options={"managed": False, "verbose_name_plural": "Learned By TM"},
        ),
        migrations.AlterModelOptions(
            name="moves",
            options={"managed": False, "verbose_name_plural": "Moves"},
        ),
        migrations.AlterModelOptions(
            name="notabletrainers",
            options={"managed": False, "verbose_name_plural": "Notable Trainers"},
        ),
        migrations.AlterModelOptions(
            name="pokedex",
            options={"managed": False, "verbose_name_plural": "Pokedex"},
        ),
        migrations.AlterModelOptions(
            name="pokemonabilities",
            options={"managed": False, "verbose_name_plural": "Pokemon Abilities"},
        ),
        migrations.AlterModelOptions(
            name="pokemonregion",
            options={"managed": False, "verbose_name_plural": "Pokemon Regions"},
        ),
        migrations.AlterModelOptions(
            name="regions",
            options={"managed": False, "verbose_name_plural": "Regions"},
        ),
    ]
